config/routes.rb
MicroTutoring::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
    root to: 'home#index'
    get 'subjects/new', to: 'subjects#new'
    post 'subjects/new', to: 'subjects#create'
    get 'subjects/:id', to: 'subjects#show', as: "subjects_show"
    get 'subjects/:id/add', to: 'courses#new'
    get 'courses/new', to: 'courses#new'
    post 'courses/new', to: 'courses#create'
    get 'courses/:id', to: 'courses#show', as: "courses_show"
    delete 'courses/:id', to: 'courses#delete', as: 'courses_delete'
    get 'courses/:id/edit', to: 'courses#edit'
    get 'users/:id' => 'users#show'
    get 'posts/new', to: 'posts#new'
    post 'posts/new', to: 'posts#create'
    delete 'posts/:id', to: 'posts#delete', as: 'posts_delete'
    delete 'subjects/:id', to: 'subjects#delete', as: 'subjects_delete'
  resources :users

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
    belongs_to :subject
    has_many :posts
    validates :number, presence: true, uniqueness: true
    validates :subject_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/models/subject.rb
class Subject < ActiveRecord::Base
    has_many :courses
    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :username, :birthday, :email, :password, :remember_me)}
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :username, :birthday, :about, :email, :password, :current_password, :remember_me)}

  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    def show
        @course = Course.find(params[:id])
    end

    def new
      @course = Course.new
    end

    def create
        subject = Subject.find_by(name: params[:course][:subject])
        if !subject
          redirect_to root_path, :flash => { :error => "Subject does not exist" }
        end
        course = Course.new(
          :number => params[:course][:number],
          :subject_id => subject.id,
          :description => params[:course][:description])
        if course.valid?
          course.save
          redirect_to root_path
        else
          #flash isn't working rn but at least it doesn't error
          redirect_to root_path, :flash => { :error => "Subject already exists" }
        end

    end

    def delete
        course = Course.find(params[:id])
        subject = Subject.find_by(id: course.subject_id)
        course.destroy
        redirect_to subjects_show_path(subject.id)
    end

    def edit
      course = Course.find(params[:id])
      #TODO: method for updating, might need to add params method to make easier
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @subjects = Subject.all
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
    end

    def create
        subject = Subject.find_by(name: params[:post][:subject])
        if subject == nil
          redirect_to root_path
        end
        course = Course.find_by(number: params[:post][:course], subject_id: subject)
        if course == nil
          redirect_to root_path
        end
        post = Post.new(
          :title => params[:post][:title],
          :course_id => course.id,
          :description => params[:post][:description],
          :bounty => params[:post][:bounty].to_i,
          :user_id => current_user.id,
          :user_email => current_user.email)
         post.save
          #flash isn't working rn but at least it doesn't error
         redirect_to courses_show_path(course.id)
    end

    def delete
        post = Post.find(params[:id])
        course = Course.find_by(id: post.course_id)
        post.destroy
        redirect_to courses_show_path(course.id)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

    def show
        @subject = Subject.find(params[:id])
    end

    def new
      @subject = Subject.new
    end

    def create
        subject = Subject.new(:name => params[:subject][:name])
      if subject.valid?
        subject.save
        redirect_to root_path
      else
        #flash isn't working rn but at least it doesn't error
        redirect_to root_path, :flash => { :error => "Subject already exists" }
      end
    end

    def delete
      subject = Subject.find(params[:id])
      subject.destroy
      #TODO: also destroy all posts!
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/new.html.erb
<%= form_for @course, url: {action: "create"} do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %> </br>
  <%= f.label :number %>
  <%= f.text_field :number %> </br>
  <%= f.label :description %>
  <%= f.text_field :description %> </br>
  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h3>Course</h3>

<h2><%= @course.number if @course.number %></h2>
<p>Description: <%= @course.description if @course.description %></p>

<h5>Posts:</h5> <% @course.posts.each do |post| %>
    <div style="border: 1px solid black; padding:10px;">
    <b> <%= post.title %> </b>
    </br><%= post.description %>
</br>$<%= post.bounty %>
    </br> Contact: <%= post.user_email %>
    <% if current_user.admin || current_user.id == post.user_id%>
        <%= button_to "Delete Post", posts_delete_path(post), :method => :delete %>
    <% end %>
    </div>
<% end %>
<%= button_to "Make Post", posts_new_path, :method => :get %>
<% if current_user.admin %>
    <%= button_to "Delete Course", courses_delete_path(@course), :method => :delete %>
<% end %>

app/views/home/index.html.erb
<h3>MicroTutoring</h3>

<p>Subjects: <% @subjects.each do |s| %>
    <li>
        Name: <%= s.name %><%= button_to "View Subject", subjects_show_path(id: s.id), :method => :get %>
    </li>
    <% end %>
</p>
<%= button_to "Add Subject", subjects_new_path, :method => :get %>
<%= button_to "Add Course", courses_new_path, :method => :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroTutoring</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding:20px;">

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<%= form_for :post, url: {action: "create"} do |f| %>
    <%= f.label :subject %>
    <%= f.text_field :subject %> </br>
    <%= f.label :course %>
    <%= f.text_field :course %> </br>
  <%= f.label :title %>
  <%= f.text_field :title %> </br>
  <%= f.label :description %>
  <%= f.text_field :description %> </br>
  <%= f.label :bounty %>
  <%= f.text_field :bounty %></br>
  <%= f.submit %>
<% end %>

app/views/subjects/new.html.erb
<%= form_for @subject, url: {action: "create"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/subjects/show.html.erb
<h3>Subject</h3>

<p>Name: <%= @subject.name %></p>

<p>Courses: <% @subject.courses.each do |c| %>
    <li>
        Number: <%= c.number %>
        Description: <%= c.description %>
        <%= button_to "View Course", courses_show_path(c.id), :method => :get %>
    </li>
    <% end %>
</p>
<%= button_to "Add Course", courses_new_path, :method => :get %>
<% if current_user.admin %>
    <%= button_to "Delete Subject", subjects_delete_path(@subject), :method => :delete %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %></h1>

<p>Username: <%= @user.username %></p>
<p>About: <%= @user.about %></p>
<p>Preferred Tutoring Subjects: <%= @user.fav_subjects %></p>